database:
  path: 'network_dependencies.db'

nmap:
  scan_arguments: "-v -n -p 22,5985"

web_server:
  host: '127.0.0.1'
  port: 5000
  debug: true

credentials:
  known_hosts_file: 'known_hosts_credentials.txt'
  generic_credentials_file: 'generic_credentials.txt'
  ssh_private_key: 'id_rsa'
  ssh_usernames: ['afonso.duarte']

network_scan:
  subnets:
    - '192.168.1.0/24'


logging:
  directory: 'logs'
  filename_format: 'log_%Y%m%d_%H%M%S.txt'
